package internal.dataAccess.DTO;

public class PostDTO{
    public String filePath;
    public String fileName;
    public String postId;// auto-generated by mongodb
    public String postAuthor;// id of the user that posted connected with Applicant userId
}
